### ISSUE TITLE
mona.config.ts 配置 devServer 没有效果

### ISSUE THREAD

**Issue by noshower** [bytedance/mona#131]
使用 chain 函数配置 devServer 没有生效。

toConfig() 显示配置了

<img width="654" alt="image" src="https://user-images.githubusercontent.com/15035094/187868316-4ce7ac0a-68df-4629-a6ec-a0ed11f8f7a8.png">

**Comment by xwchris** [comment]
什么场景需要配置devServer呀

**Comment by noshower** [comment]
开发环境，难道要用 nginx ？

开发时不一定要在 飞鸽容器内

**Comment by xwchris** [comment]
直接start默认就会启用devServer

**Comment by noshower** [comment]
` const devServer = new WebpackDevServer(
          {
            static: {
              directory: staticDir,
            },
            headers: {
              'Access-Control-Allow-Origin': '*',
            },
            hot: true,
            open: true,
            historyApiFallback: true,
            compress: true,
            port,
            allowedHosts: 'all',
            host: DEFAULT_HOST,
            client: {
              overlay: {
                errors: true,
                warnings: false
              }
            }
          },
          compiler,
        );

        devServer.startCallback(() => {
          console.log(chalk.green(`服务启动成功： http://${DEFAULT_HOST}:${port}`));
        });`

代码里写死了。

**Comment by xwchris** [comment]
是的，你需要额外配置什么东西吗？proxy?

**Comment by noshower** [comment]
是的。我觉得交给开发者自定义可能更好点

**Comment by xwchris** [comment]
有这个需求，我们可以漏下这个配置，等上线通知你

**Comment by noshower** [comment]
辛苦

**Comment by xwchris** [comment]
#134

**Comment by xwchris** [comment]
> 是的。我觉得交给开发者自定义可能更好点

0.2.15版本，mona.config.ts增加dev选项，可以配置devServer
