### ISSUE TITLE
[feature] 期望可以指定 app.config.ts

### ISSUE THREAD

**Issue by noshower** [bytedance/mona#140]
**需求描述**

我们要复用之前的项目，之前的项目已经存在 app.config.js 文件，如果要支持 mona, 需要改名（虽然很简单）。 如果可以，最好能够新增命令参数，用来指定 app.config.js 文件。

**解决方案**
可选
**其他信息**
如截图等可以贴在这里

**Comment by bWhirring** [comment]
新版本运行 `-c **.ts` 指定配置文件
