### ISSUE TITLE
[feature] 期望可以指定 publicPath

### ISSUE THREAD

**Issue by noshower** [bytedance/mona#141]
**需求描述**
目前 copyPublicPlugin copy 的是 public 目录，实际项目中，我们会使用其他目录，原因是 public 已经被占用了。

期望，copy 的目录可以用户自定义

**解决方案**
可选
**其他信息**
如截图等可以贴在这里

**Comment by noshower** [comment]
所有脚手架都支持修复 public 路径，应该是比较场景的需求

**Comment by xwchris** [comment]
目前无法支持
