### ISSUE TITLE
编译小程序无法预览，也无法使用小程序开发工具预览

### ISSUE THREAD

**Issue by dreamsSilent** [bytedance/mona#148]
编译小程序无法预览，也无法使用小程序开发工具预览

**其他信息**
使用mona init 初始化项目
![image](https://user-images.githubusercontent.com/39482126/189474672-1f6fa044-142d-43d7-8c4d-6ebbba7b26b1.png)

选择模版
 app（适用于商家应用开发支持小程序和h5） 
yarn start:mini启动项目\ yarn build:mini
打包生成dist
![image](https://user-images.githubusercontent.com/39482126/189474750-e46a4c39-678c-48cb-a7fd-b15675446772.png)

并不是小程序文件，ide并不能预览，只能浏览器预览，但是有些小程序相关API无法调用调试。

希望能够支持小程序开发工具预览或者支持其他预览方式调试

**Comment by xwchris** [comment]
模板有点问题，写成这样
