### ISSUE TITLE
[BUG] mona init 的项目在飞鸽客服系统打不开

### ISSUE THREAD

**Issue by noshower** [bytedance/mona#150]
**bug 描述**
[详细地描述 bug]
今天，我们项目升级了依赖，然后就报下面的错误。

然后使用 mona init 生成的项目，在飞鸽客服系统打开也报错。

![image](https://user-images.githubusercontent.com/15035094/190066754-ce5f94b2-3db9-4ebe-ac87-a581f38f3706.png)
![image](https://user-images.githubusercontent.com/15035094/190066854-7aaddd6d-215e-4c97-9d1f-98d02acdf104.png)

帮忙紧急修复下，今天等着上线呢。

**版本信息:**

- mona 版本: 1.0.0
- 开发环境: mac OS
- node版本(可选): 16.14.0
- npm 版本(可选): 8.5.0

**复现步骤**

**期望结果**

**复现代码**
可复现问题的代码片段/代码仓库
```js
// 复现问题的代码
```

**其他信息**
如截图等可以贴在这里

**Comment by xwchris** [comment]
先用0.2.26或者再mona.config.ts中设置

**Comment by noshower** [comment]
ok
